[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_ai_lib"
version = "0.1.0"
description = "Custom AI helper library"
authors = [{ name = "Afwana Nazer" }]
dependencies = []